Repository realm/realm-kotlin, pull requests merged in 2023-09, with the labels that each got.

#1491 Add support for automatic resetting incremental backoff when network status changes
  CHANGELOG.md
  packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmInstantImpl.kt
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
  packages/library-base/src/jvm/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
  packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
  packages/library-sync/src/androidMain/AndroidManifest.xml
  packages/library-sync/src/androidMain/kotlin/io/realm/kotlin/mongodb/internal/NetworkStateObserver.kt
  packages/library-sync/src/androidMain/kotlin/io/realm/kotlin/mongodb/internal/RealmSyncInitializer.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/App.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppImpl.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/NetworkStateObserver.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncImpl.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/Sync.kt
  packages/library-sync/src/jvmMain/kotlin/io/realm/kotlin/mongodb/internal/NetworkStateObserver.kt
  packages/library-sync/src/nativeDarwin/kotlin/io/realm/kotlin/mongodb/internal/NetworkStateObserver.kt
  packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/ApiKeyAuthTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppConfigurationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AsymmetricSyncTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/CredentialsTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/EmailPasswordAuthTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncConfigurationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncIntegrationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FunctionsTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/HttpLogObfuscatorTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/MutableSubscriptionSetTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/ProgressListenerTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionExtensionsTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionSetTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientResetIntegrationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncConfigTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncSessionTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/UserProfileTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/UserTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/nonlatin/NonLatinTests.kt
  packages/test-sync/src/jvmTest/kotlin/io/realm/kotlin/test/mongodb/jvm/RealmTests.kt
Labels: cla: yes

#1503 Fix missing scheduler on Linux and Windows (JVM)
  CHANGELOG.md
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
  packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
  packages/jni-swig-stub/src/main/jni/realm_api_helpers.h
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/types/annotations/FullText.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/VersionTrackingTests.kt
Labels: cla: yes

#1506 Update BAAS test server version
  dependencies.list
  packages/test-base/src/commonMain/kotlin/io/realm/kotlin/test/util/Utils.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncIntegrationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FunctionsTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionSetTests.kt
Labels: cla: yes, no-changelog

#1509 Fix test around releasing intermediate versions
  packages/test-base/src/androidInstrumentedTest/kotlin/io/realm/kotlin/test/android/MemoryTests.kt
Labels: cla: yes, no-changelog

#1512 Test with Kotlin 1.9.20-Beta
  buildSrc/src/main/kotlin/Config.kt
Labels: no-changelog

#1517 Fix redirects only working for GET requests.
  CHANGELOG.md
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/HttpClientCache.kt
  packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/util/HttpClient.kt
Labels: cla: yes

#1514 Remove Realm Plugin setting the bytecode target to 1.8
  CHANGELOG.md
  benchmarks/androidApp/build.gradle.kts
  benchmarks/build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Config.kt
  buildSrc/src/main/kotlin/realm-lint.gradle.kts
  examples/kmm-sample/androidApp/build.gradle.kts
  examples/kmm-sample/compose-desktop/build.gradle.kts
  examples/realm-java-compatibility/app/build.gradle
  integration-tests/gradle-plugin-test/single-platform/build.gradle.kts
  packages/build.gradle.kts
  packages/cinterop/build.gradle.kts
  packages/gradle-plugin/build.gradle.kts
  packages/gradle-plugin/src/main/kotlin/io/realm/kotlin/gradle/RealmPlugin.kt
  packages/jni-swig-stub/build.gradle.kts
  packages/library-base/build.gradle.kts
  packages/library-sync/build.gradle.kts
  packages/plugin-compiler-shaded/build.gradle.kts
  packages/plugin-compiler/build.gradle.kts
  packages/test-base/build.gradle.kts
  packages/test-sync/build.gradle.kts
Labels: cla: yes

#1518 Fix SyncConfig tests that would break on Windows
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmConfigurationTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppConfigurationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncConfigurationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncConfigTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
Labels: cla: yes, no-changelog

#1523 Fix error in RealmAny.equals when comparing similarly typed object
  CHANGELOG.md
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmAnyImpl.kt
  packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/SerializableSample.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmAnyTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/SerializationTests.kt
Labels: cla: yes

#1515 Cleanup resources better during Client Reset and closing Realms.
  CHANGELOG.md
  dependencies.list
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
  packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmImpl.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/ClientResetRequiredException.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncConfigurationImpl.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncSessionImpl.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncedRealmContext.kt
  packages/test-base/src/androidMain/kotlin/io/realm/kotlin/test/platform/PlatformUtils.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmTests.kt
  packages/test-sync/build.gradle.kts
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AsymmetricSyncTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncIntegrationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/MutableSubscriptionSetTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/ProgressListenerTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/Schema.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionExtensionsTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionSetTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientResetIntegrationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncConfigTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncSessionTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/nonlatin/NonLatinTests.kt
Labels: cla: yes
