Repository realm/realm-kotlin, pull requests merged in 2023-11, with the labels that each got.

#1525 K2 support
  CHANGELOG.md
  Jenkinsfile
  buildSrc/src/main/kotlin/Config.kt
  examples/kmm-sample/shared/build.gradle.kts
  integration-tests/gradle-plugin-test/multi-platform/src/nativeTest/kotlin/io/realm/test/multiplatform/util/platform/PlatformUtils.kt
  packages/cinterop/build.gradle.kts
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
  packages/cinterop/src/nativeDarwinTest/kotlin/io/realm/kotlin/test/CinteropTest.kt
  packages/library-base/build.gradle.kts
  packages/library-sync/src/androidMain/kotlin/io/realm/kotlin/mongodb/internal/RealmSyncInitializer.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/MutableSubscriptionSetImpl.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SubscriptionImpl.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncConfigurationImpl.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SyncSessionImpl.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Identifiers.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/IrUtils.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticMethodsExtension.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Registrar.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/fir/RealmPluginGeneratorKey.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/fir/model/CompanionExtension.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/fir/model/ObjectExtension.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/fir/model/RealmModelRegistrar.kt
  packages/test-base/build.gradle.kts
  packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/SerializableSample.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmSchemaTests.kt
  packages/test-base/src/nativeDarwinTest/kotlin/io/realm/kotlin/test/darwin/CoroutineTests.kt
  packages/test-base/src/nativeDarwinTest/kotlin/io/realm/kotlin/test/darwin/MemoryTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FunctionsTests.kt
Labels: cla: yes

#1571 DynamicObjects can now access fields by public name.
  packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/Sample.kt
  packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/migration/Sample.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/PersistedNameTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/migration/RealmMigrationTests.kt
Labels: no-changelog

#1573 Fail build if metric collection fails on CI
  Jenkinsfile
  examples/min-android-sample/build.gradle.kts
  examples/min-android-sample/gradle.properties
Labels: no-changelog

#1533 Add geo types sync integration tests.
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/UserImpl.kt
  packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/GeoEntities.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/GeoSpatialTests.kt
  packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/entities/sync/SyncRestaurant.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AsymmetricSyncTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/FlexibleSyncIntegrationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/GeoSpatialTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/MutableSubscriptionSetTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/ProgressListenerTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/Schema.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionExtensionsTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionSetTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SubscriptionTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientResetIntegrationTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncClientTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncConfigTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncSessionTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/UserTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/nonlatin/NonLatinTests.kt
Labels: cla: yes, no-changelog

#1579 Fix corner cases in tests discovered after running on Github Actions
  benchmarks/settings.gradle.kts
  buildSrc/src/main/kotlin/Config.kt
  examples/kmm-sample/settings.gradle.kts
  examples/realm-java-compatibility/settings.gradle.kts
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/Configuration.kt
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ConfigurationImpl.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/Decimal128Tests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/EmbeddedRealmObjectTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/FqNameImportTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/ImportTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/LinkTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/NullabilityTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/ReadMeTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmConfigurationTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmInMemoryTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/migration/RealmMigrationTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmNotificationsTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/SystemNotificationTests.kt
  packages/test-base/src/jvmMain/kotlin/io/realm/kotlin/test/platform/PlatformUtils.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/jvm/RealmTests.kt
Labels: no-changelog
