Repository realm/realm-kotlin, pull requests merged in 2024-04, with the labels that each got.

#1699 [RKOTLIN-825] Remove unused docker image
  Dockerfile.android
Labels: cla: yes, no-changelog

#1717 Update URL to documentation
  CHANGELOG.md
  README.md
Labels: cla: yes, no-jira-ticket

#1718 RKOTLIN-1033: Update default base url
  CHANGELOG.md
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/AppConfiguration.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/AppConfigurationTests.kt
Labels: cla: yes

#1721 Support for compiling the SDK with Kotlin 2
  CHANGELOG.md
  packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/ErrorCategory.kt
  packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/ErrorCode.kt
  packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/sync/ProtocolErrorCode.kt
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/ErrorCategory.kt
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/ErrorCode.kt
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/sync/ProtocolErrorCode.kt
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/ErrorCategory.kt
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/ErrorCode.kt
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/sync/ProtocolErrorCode.kt
  packages/gradle-plugin/src/main/kotlin/io/realm/kotlin/gradle/RealmCompilerSubplugin.kt
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ConfigurationImpl.kt
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmConfigurationImpl.kt
  packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
  packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/WeakReference.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/AccessorModifierIrGeneration.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/IrUtils.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelLoweringExtension.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/SyncLoweringExtension.kt
  packages/plugin-compiler/src/test/kotlin/io/realm/kotlin/compiler/GenerationExtensionTest.kt
  packages/plugin-compiler/src/test/resources/sample/expected/01_AFTER.ValidateIrBeforeLowering.ir
  packages/plugin-compiler/src/test/resources/schema/expected/01_AFTER.ValidateIrBeforeLowering.ir
  packages/test-base/src/jvmMain/kotlin/io/realm/kotlin/test/util/Compiler.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/BacklinksTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/CollectionTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/CyclicDependenciesTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/EmbeddedTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/FullTextTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/IndexTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/ModelDefinitionTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/PersistedNameTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/PrimaryKeyTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/RealmObjectAsGenericTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/Utils.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/dictionary/DictionaryTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/list/ListTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/set/SetTests.kt
  packages/test-sync/build.gradle.kts
  packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/nonlatin/NonLatinTests.kt
  packages/test-sync/src/jvmTest/kotlin/io/realm/kotlin/test/mongodb/compiler/AsymmetricObjectTests.kt
  packages/test-sync/src/jvmTest/kotlin/io/realm/kotlin/test/mongodb/jvm/RealmTests.kt
Labels: cla: yes, no-jira-ticket

#1727 Support compiling the SDK with Kotlin 2 (#1721)
  CHANGELOG.md
  packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/ErrorCategory.kt
  packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/ErrorCode.kt
  packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/sync/ProtocolErrorCode.kt
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/ErrorCategory.kt
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/ErrorCode.kt
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/sync/ProtocolErrorCode.kt
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/ErrorCategory.kt
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/ErrorCode.kt
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/sync/ProtocolErrorCode.kt
  packages/gradle-plugin/src/main/kotlin/io/realm/kotlin/gradle/RealmCompilerSubplugin.kt
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/ConfigurationImpl.kt
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmConfigurationImpl.kt
  packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/SystemUtils.kt
  packages/library-base/src/nativeDarwin/kotlin/io/realm/kotlin/internal/platform/WeakReference.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/AccessorModifierIrGeneration.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/IrUtils.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelLoweringExtension.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/RealmModelSyntheticPropertiesGeneration.kt
  packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/SyncLoweringExtension.kt
  packages/plugin-compiler/src/test/kotlin/io/realm/kotlin/compiler/GenerationExtensionTest.kt
  packages/plugin-compiler/src/test/resources/sample/expected/01_AFTER.ValidateIrBeforeLowering.ir
  packages/plugin-compiler/src/test/resources/schema/expected/01_AFTER.ValidateIrBeforeLowering.ir
  packages/test-base/src/jvmMain/kotlin/io/realm/kotlin/test/util/Compiler.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/BacklinksTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/CollectionTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/CyclicDependenciesTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/EmbeddedTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/FullTextTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/IndexTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/ModelDefinitionTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/PersistedNameTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/PrimaryKeyTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/RealmObjectAsGenericTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/Utils.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/dictionary/DictionaryTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/list/ListTests.kt
  packages/test-base/src/jvmTest/kotlin/io/realm/kotlin/test/compiler/set/SetTests.kt
  packages/test-sync/build.gradle.kts
  packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/TestApp.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/nonlatin/NonLatinTests.kt
  packages/test-sync/src/jvmTest/kotlin/io/realm/kotlin/test/mongodb/compiler/AsymmetricObjectTests.kt
  packages/test-sync/src/jvmTest/kotlin/io/realm/kotlin/test/mongodb/jvm/RealmTests.kt
Labels: cla: yes, no-jira-ticket
