Repository realm/realm-kotlin, pull requests merged in 2024-03, with the labels that each got.

#1672 Add subscription state and tests
  CHANGELOG.md
  packages/cinterop/src/androidInstrumentedTest/kotlin/io/realm/kotlin/test/sync/SyncEnumTests.kt
  packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/sync/CoreSubscriptionSetState.kt
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/sync/CoreSubscriptionSetState.kt
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/sync/CoreSubscriptionSetState.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/BaseSubscriptionSetImpl.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/sync/SubscriptionSetState.kt
Labels: cla: yes

#1664 Guard analytics errors from breaking build
  .github/workflows/include-integration-tests.yml
  .github/workflows/pr.yml
  CHANGELOG.md
  packages/gradle-plugin/src/main/kotlin/io/realm/kotlin/gradle/RealmCompilerSubplugin.kt
Labels: cla: yes

#1679 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/check-pr-title.yml
  .github/workflows/issue-labeler.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#1663 Automate release process to Maven Central and Gradle Plugin Portal
  .github/workflows/include-deploy-release.yml
  .github/workflows/include-deploy-snapshot.yml
  .github/workflows/pr.yml
  CHANGELOG.md
Labels: cla: yes

#1680 Fetching all tags for release check
  .github/workflows/pr.yml
Labels: cla: yes

#1681 Fixing GHA check-release logic
  .github/workflows/pr.yml
Labels: cla: yes

#1683 Fixing release script
  tools/publish_release.sh
Labels: cla: yes

#1689 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/lock-threads.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#1666 Fix list indexof, remove and contains
  CHANGELOG.md
  packages/cinterop/src/commonMain/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
  packages/cinterop/src/jvm/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
  packages/cinterop/src/nativeDarwin/kotlin/io/realm/kotlin/internal/interop/RealmInterop.kt
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/RealmListInternal.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmAnyNestedCollectionTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/RealmListTests.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmAnyNestedListNotificationTest.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmListNotificationsTests.kt
Labels: cla: yes

#1694 [RKOTLIN-1037] Copy missing JVM binaries (Win/Linux) when releasing
  .github/workflows/include-deploy-release.yml
  .github/workflows/pr.yml
  CHANGELOG.md
Labels: cla: yes

#1696 [RKOTLIN-1040] Fixing doc mime type
  packages/build.gradle.kts
Labels: cla: yes, no-changelog

#1698 [RKOTLIN-825] Removing Jenkins switching to Github Action for CI/CD
  CHANGELOG.md
  Jenkinsfile
  benchmarks/settings.gradle.kts
  buildSrc/src/main/kotlin/Config.kt
  buildSrc/src/main/kotlin/realm-lint.gradle.kts
  examples/kmm-sample/settings.gradle.kts
  examples/realm-java-compatibility/settings.gradle.kts
  packages/cinterop/build.gradle.kts
Labels: cla: yes

#1710 [RKOTLIN-1062] Remove CMake required version
  CHANGELOG.md
  buildSrc/src/main/kotlin/Config.kt
  packages/cinterop/build.gradle.kts
Labels: cla: yes
