Repository realm/realm-kotlin, pull requests merged in 2024-06, with the labels that each got.

#1768 [RKOTLIN-1096] Map `is_fatal` to `UnrecoverableSyncException`
  CHANGELOG.md
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/RealmSyncUtils.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
Labels: cla: yes

#1778 [RKOTLIN-1102] Remove nullability check in `SubscriptionSetImpl.waitForSynchronization`
  .github/workflows/include-check-cache.yml
  CHANGELOG.md
  packages/library-base/src/commonMain/kotlin/io/realm/kotlin/exceptions/RealmException.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/AppException.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/exceptions/SyncExceptions.kt
  packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/SubscriptionSetImpl.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/CredentialsTests.kt
Labels: cla: yes

#1758 Use mac arm runners on GHA
  .github/workflows/pr.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#1783 [RKOTLIN-833] Add collection in mixed sync roundtrip tests
  packages/test-base/src/commonMain/kotlin/io/realm/kotlin/entities/JsonStyleRealmObject.kt
  packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmAnyNestedCollectionNotificationTest.kt
  packages/test-sync/src/commonMain/kotlin/io/realm/kotlin/test/mongodb/common/Schema.kt
  packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt
Labels: cla: yes, no-changelog

#1775 Add kotlin problem matchers
  .github/problem-matchers/detekt.json
  .github/problem-matchers/kotlin.json
  .github/problem-matchers/ktlint.json
  .github/workflows/auto-merge-branches.yml
  .github/workflows/include-check-cache.yml
  .github/workflows/include-deploy-release.yml
  .github/workflows/include-deploy-snapshot.yml
  .github/workflows/include-integration-tests.yml
  .github/workflows/include-static-analysis.yml
  .github/workflows/pr.yml
  buildSrc/src/main/kotlin/realm-lint.gradle.kts
Labels: cla: yes, no-changelog, no-jira-ticket
